### ISSUE TITLE
抓取请求头不需要Cookie

### ISSUE THREAD

**Issue by Nelocompne** [cangkongman/crawling-bilibili-personal-collect#3]
抓取公开收藏夹的信息api请求头不需要Cookie。如果非要用请求头，可以使用`SESSDATA=xxx`，来自bilibili-API-collect中示例使用的请求头。同时代码里暴露了个人的Cookie，强烈建议重新审计代码中的authentication信息。

**Comment by cangkongman** [comment]
感谢感谢，已经删掉了
