### ISSUE TITLE
获取不到番剧，电影，纪录片之类视频的up主信息

### ISSUE THREAD

**Issue by doubilbm** [cangkongman/crawling-bilibili-personal-collect#4]
目前已知番剧，电视剧，国创，纪录片，电影，综艺都获取不到
![0](https://user-images.githubusercontent.com/62131661/208798005-e9078fc9-56e0-4416-a80e-1575de39774e.jpg)
如图上这几个视频在头像那一步就会报错，请问除了取消收藏之外还有什么解决办法吗？

**Comment by cangkongman** [comment]
优质回答：我不知道，你f12自己看看吧

**Comment by doubilbm** [comment]
> 优质回答：我不知道，你f12自己看看吧

....好吧，打扰了
